const logs = [
    "[IRAN] REZA_PAHLAVI_POPULAR_SUPPORT",
    "[VOICE] MILLIONS_CHANT_HIS_NAME",
    "[HOPE] CALL_FOR_HIS_RETURN",
    "[UNITY] IRANIANS_STAND_TOGETHER",
    "[FREEDOM] زن_زندگی_آزادی"
];
